### ISSUE TITLE
Unraid issue with permissions

### ISSUE THREAD

**Issue by pallebone** [11notes/docker-unifi#11]
On Unraid the permissions of this docker do not work correctly without some changes that must be manually made. This is because Unraid expects it to run as 99:100

There are some possible ways to resolve it here are some options:

1) create a separate image on dockerhub that is specific to unraid. Eg: if you look at this docker there are different tags for an ubuntu based image vs an alpine based image:
https://hub.docker.com/r/goofball222/unifi/tags

This has the advantage of keeping things separate and so a breakage in 1 image might not roll over to a different one and so on, however I believe it might create more work for you.

2) Second option is to pass some values to the image on deployment eg: -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='002'
This can be passed and if the docker expects them, can make accommodation to run with the values passed. 

This might be an easier way to complete the task, but does introduce more complexity/possible breakage is increased.

What are your thoughts on this? Would you consider such ideas to improve compatibility or is this outside what you would consider. If it is something you would consider, what approach would you prefer? I personally have seen a separate tag working well in the past for others, but I don't know how much effort that is for you and wouldn't want to suggest a difficult option.

Many thanks for your time,
Pete

**Comment by 11notes** [comment]
Here: **11notes/unifi:7.5.187-unraid**, give it a try and report back

**Comment by pallebone** [comment]
Wow, initial tests look good. I will report back after I have reconfigured the community app and got a few people to test, THANKS!!!!!!!!!!!!!!!

**Comment by pallebone** [comment]
I am just waiting on people to test but one thing ai would mention is that none of the unraid users will ever use the tag:latest. 

I notices on your readme page the latest tag has updated to “version
v7.5.187-unraid”. 

if some of your users use the tag latest you should check this wont cause an issue and also structure the updates of the images in such a way that unraid is updated, then your normal image immediately after ao unraid is never the latest tag. 

Hope this makes sense. Not telling you what to do obviously. Just mentiining this incase you overlooked it and didnt intend this to happen, and its also possible I am incorrect in my interpretation so please feel free to correct me also 😳😀

**Comment by 11notes** [comment]
I don’t do the tag latest on all my images. Every image has always a version tag. If you need a latest tag I could create another repo on ducker hub just for unraid.

**Comment by pallebone** [comment]
No we dont need, thanks :)

**Comment by pallebone** [comment]
So far 3 people have managed to use this new tag without any issues whatsoever. I expect that when the message warning peoole yhe old container is deprecated we will get hundreds of more people all in a row so for now I will close this ticket as it appears fully resolved. Just have to wait until January now. 

Thanks! 😀
