### ISSUE TITLE
Backup/Restore process has a java issue/exception but still completes.

### ISSUE THREAD

**Issue by pallebone** [11notes/docker-unifi#12]
When you backup a config, then deploy this docker image from scratch you can on first login to the web page choose restore.

If you do this, and restore, the docker stops after restoring but throws an error. If you then start it again then it functions correctly and has restored..

I believe the image should start itself up again automatically but is not doing so. Is this an error that Unifi has to fix?

Error:
https://upload.forums.unraid.net/live/monthly_2023_11/image.png.34a982977c9807987f2d00316da6fed7.png

**Comment by pallebone** [comment]
Just want to confirm this is a unifi issue :)

**Comment by bmartino1** [comment]
Linux Server was using a automated task to handle it when it was running unfi made database similar to redis / mysql. the ubiquity group no longer wanted to support their own database and opted to follow the mongdb database as it handle the same request.

As such the previous automation with linux server and how the database was to be handled didn't have a export nor option to use the MongoDB database. That was Linux IO way to EOL the docker.

Its more on ubquity not wanting to manage and maintain the database and has licensed mondb with a lifetime suport on version 3.6

https://www.reddit.com/r/Ubiquiti/comments/16d6rpq/unifi_still_requiring_mongodb_36_is_again/
https://community.ui.com/questions/Supported-Mongodb-version-is-EOL/6a97712b-2a58-4d96-8733-14b18c3ca063

My understanding is that unifi support license expired, they tried to make a DB jump and failed. Then went back to mongodb

During this time unfi removed the built in mongdb from with in the unifi package. Hence, we now install mondb on the side and maintain it from mongdb release cycles.
