### ISSUE TITLE
v 8.0.7 is now official

### ISSUE THREAD

**Issue by pallebone** [11notes/docker-unifi#13]
Network controller v 8.0.7 is now released and official.

Kind regards
Peter

**Comment by 11notes** [comment]
Hi Peter. I always test a new release on my own installation (private) first for a few days before I push the image to the public. So far, I did not see any issues. 8.0.7 is therefore pushed to docker hub.

**Comment by pallebone** [comment]
> Hi Peter. I always test a new release on my own installation (private) first for a few days before I push the image to the public. So far, I did not see any issues. 8.0.7 is therefore pushed to docker hub.

Ok thank you. That is noted and makes sense. Many thanks :)
P

**Comment by pallebone** [comment]
I have updated the unraid post where users find this docker with the following information to ensure you have the time you require to test:

"When a new release is available from unifi, the first 7 days after it is release are reserved for internal testing. No tag will be made available until after 7 days irrespective of how many people complain they really need the new version right now. Deal with it."

**Comment by pallebone** [comment]
@11notes - A word of thanks, users have started using the new tag and reported no issues. Thank you :)
