### ISSUE TITLE
Docker tag 8.1.113-unraid has somehow updated to 8.1.127

### ISSUE THREAD

**Issue by pallebone** [11notes/docker-unifi#16]
On https://hub.docker.com/r/11notes/unifi/tags the 8.1.113 tag was somehow updated and has pushed 8.1.127 inadvertently to all unraid users. Did an error occur with the build?

I dont suggest reverting as now a bunch of users on 8.1.113 tag have auto updated to the 8.1.127 version. Just looking for clarification as to what happened.

Kind regards
P

**Comment by jonathanm-ur** [comment]
For those that don't update automatically or quickly, can a new tag be generated with the 8.1.113 version? That way those that didn't update can change to a tag that genuinely should stay at 8.1.113?

Maybe 8.1.113-unraid-fixed

**Comment by 11notes** [comment]
There was an issue with the CI/CD that used the old tag with the new build, this got fixes, but for the reason @ [jonathanm-ur](https://github.com/jonathanm-ur) wrote, I’m not going to repush 1.113 with the correct version because of breaking changes.

**Comment by pallebone** [comment]
Hi @11notes 

Can you clarify what the CI/CD is?

Also are you saying there will be no way to tag the 8.1.113 version going forward?

Kind regards
P

**Comment by 11notes** [comment]
Simple typo, that resulted in 1.113 being tagged but 1.127 being deployed. If I now add 1.113 back again, and people have 1.113 as 1.127 with the 1.113 tag, there is a risk of downgrading their installation. Since Unifi moves pretty fast, I just remove the 1.113 tag since 1.127 is current release anyway.

**Comment by pallebone** [comment]
Ok thanks, makes sense.
