### ISSUE TITLE
compose file

### ISSUE THREAD

**Issue by bmartino1** [11notes/docker-unifi#20]
can we have a file made and added to the repo?

a compose file for latest release?

Example
https://forums.unraid.net/topic/147455-support-unifi-controller-unifi-unraid-reborn/?do=findComment&comment=1459993

**Comment by 11notes** [comment]
There is a compose: https://github.com/11notes/docker-unifi/blob/master/compose.yaml

**Comment by bmartino1** [comment]
Thank you, missed it when assisting someone else.
