### ISSUE TITLE
Unifi CVE

### ISSUE THREAD

**Issue by bmartino1** [11notes/docker-unifi#21]
https://community.ui.com/releases/Security-Advisory-Bulletin-042-042/c4f68b56-cdc4-4128-b2cb-5870209d1704

Any chance we can get an update to v8.4.59 sooner?

I'm a Unraid hobbyist and current Unraid maintainer for the LXC template variant.
lxc code here: https://github.com/bmartino1/unraid-lxc-unifi

not sure what you would need to make a latest / test branch that would auto update the application as done in the lxc.

**Comment by 11notes** [comment]
> Any chance we can get an update to v8.4.59 sooner?

Done.

**Comment by bmartino1** [comment]
Thank you!
