### ISSUE TITLE
V8.6.3

### ISSUE THREAD

**Issue by olympia** [11notes/docker-unifi#23]
I see that you’ve just built v8.5.6, but would there be any chance to also build rhe lateat v8.6.3 came out this morning in the normal early access branch of unifi network?

i am participting in a tester group testing a new U7 Pro and Pro Max AP firmware supposed to fix the well known IoT device connectivity issues on 2.4Ghz and rhis new firmware requires v8.6.3 unifi network.

**Comment by 11notes** [comment]
Done. Just be aware that I will not by default produce EA images.

**Comment by olympia** [comment]
Many thanks Pete!

**Comment by 11notes** [comment]
> Many thanks Pete!

My name is not Pete  😉
